### ISSUE TITLE
INPC001 should not warn here

### ISSUE THREAD

**Issue by dominicshaw** [DotNetAnalyzers/PropertyChangedAnalyzers#100]
![image](https://user-images.githubusercontent.com/2436870/49287500-9c09ea00-f495-11e8-822c-0db6b74333b6.png)

This class is an auto-generated file from autorest which creates a httpclient. It does not use INPC and has nothing to do with the VMs. Not sure why it is warning here.

**Comment by JohanLarsson** [comment]
As written the analyzer warns on all classes with public or internal mutable properties. That does not mean it is right, how should we detect that this code is generated and exclude it?

Thanks for reporting!

**Comment by JohanLarsson** [comment]
> I would suggest that if it does not implement INotifyPropertyChanged then it should not warn

The idea behind the analyzer is to enable the code fix that implements `INotifyPropertyChanged`. It nags as soon as a type has a mutable property. The reason it is written like this is so that we can trust every mutable property to notify about changes.

Simplest fix is to special case and flag things subclassing `ServiceClient<T>` as generated and excluded from checks. Not very elegant.

**Comment by JohanLarsson** [comment]
One really simple solution is to configure `INPC001` to have severity hidden.

![image](https://user-images.githubusercontent.com/1640096/52853296-78ad1d80-311b-11e9-8322-064597e4a100.png)

Hidden means teh code fix will be offered when the mouse cursor is on the class name but there will be no warning nor squiggle.

**Comment by dominicshaw** [comment]
Quite right - I thought this was also what told me if properties in classes that implemented INPC should notify but that is a separate warning. 

Hiding INPC001 does everything I want. Thanks!
