### ISSUE TITLE
INPC002 - warning that notification is not happening for property, when notification is handled by baseclass

### ISSUE THREAD

**Issue by Insire** [DotNetAnalyzers/PropertyChangedAnalyzers#17]
The following method gets a warning, that the notification is missing, when thats actually being handled via SetValue, which is provided by one of the base classes.
```cs
private int _sequence;
public int Sequence
{
	get { return _sequence; }
	set { SetValue(ref _sequence, value, OnChanged: () => Model.Sequence = value); }
}
```

This is a case of multi inheritance, aka there are 3 base types that are involed in this.

**Comment by JohanLarsson** [comment]
I'll try to repro it, I I fail I'll ask for more code. Don't worry about dumping big chunks of code in issues. Awesome for writing tests if the issue contains a full repro.

**Comment by JohanLarsson** [comment]
The reason you are getting the warning here is because in one of the overrides of `SetValue` you have side effects and notify about other properties changing. The analyzer then short circuits and reports that the property is not notified for.

We can walk all execution paths and figure out if any of them notifies about the current property but I'm not sure if it is a good idea for two reasons:
1) It will hurt perf to do excessive walking, an innocent invocation can be the start of a long chain.
2) The side effects and notifying about other properties is not super clean design. My thinking is it is good if the analyzer only understands straightforward code which would gently push us to write simpler code.

**Comment by JohanLarsson** [comment]
Not enough code to repro.
